services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        HTTP_PROXY: ${HTTP_PROXY-}
        HTTPS_PROXY: ${HTTPS_PROXY-}
        NO_PROXY: ${NO_PROXY-}
    environment:
      - HTTP_PROXY=${HTTP_PROXY-}
      - HTTPS_PROXY=${HTTPS_PROXY-}
      - NO_PROXY=dynamodb-local,${NO_PROXY-}
      - http_proxy=${HTTP_PROXY-}
      - https_proxy=${HTTPS_PROXY-}
      - no_proxy=dynamodb-local,${NO_PROXY-}
      - UV_LINK_MODE=copy 
    depends_on:
      - dynamodb-local
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    user: root # ボリュームマウントしたフォルダに書き込めるように
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local

volumes:
  dynamodb-data: